"""add_full_pipeline_columns

Revision ID: 0a1e222eec57
Revises: 
Create Date: 2026-05-25 15:19:10.006417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a1e222eec57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_clerk_org_id'), 'tenants', ['clerk_org_id'], unique=True)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('competitor_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_markdown', sa.Text(), nullable=True),
    sa.Column('scraper_method', sa.String(length=20), nullable=True),
    sa.Column('json_structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seo_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aeo_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ux_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitor_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('psychology_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_diagnosis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('autofix_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('overall_health_score', sa.Float(), nullable=True),
    sa.Column('agent_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_status'), 'analysis_reports', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_reports_tenant_id'), 'analysis_reports', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_analysis_reports_user_id'), 'analysis_reports', ['user_id'], unique=False)
    op.create_table('blueprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('business_input', sa.Text(), nullable=False),
    sa.Column('business_understanding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdp_research', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_blueprint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprints_status'), 'blueprints', ['status'], unique=False)
    op.create_index(op.f('ix_blueprints_tenant_id'), 'blueprints', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_blueprints_user_id'), 'blueprints', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blueprints_user_id'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_tenant_id'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_status'), table_name='blueprints')
    op.drop_table('blueprints')
    op.drop_index(op.f('ix_analysis_reports_user_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_tenant_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_status'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_clerk_org_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
